#include <cstddef>
#include <gtest/gtest.h>
#include <string>
#include <vector>

// This struct matches what CMake generated
struct ResourceEntry_t
{
  std::string name;
  const char* data;
  size_t size;
};

// Extern declaration of the function generated by CMake
extern std::vector<ResourceEntry_t> getAllResources();

class ResourceTest : public ::testing::TestWithParam<ResourceEntry_t>
{
};

TEST_P(ResourceTest, DataIsIntegrityChecked)
{
  const auto& res = GetParam();

  SCOPED_TRACE("Testing resource: " + res.name);

  // 1. Ensure data pointer isn't null
  ASSERT_NE(res.data, nullptr);

  // 2. Ensure size is greater than zero
  EXPECT_GT(res.size, 0);

  // 3. Verify Null Termination (since we added 0x00 in the script)
  EXPECT_EQ(res.data[res.size - 1], '\0')
    << "Resource " << res.name << " is not null-terminated!";

  // 4. Basic sanity check (e.g., first byte shouldn't be null unless file is empty)
  if(res.size > 1)
  {
    EXPECT_NE(res.data[0], '\0');
  }
}

// This "instantiates" the test for every item in our registry
INSTANTIATE_TEST_SUITE_P(
  AllFiles,
  ResourceTest,
  ::testing::ValuesIn(getAllResources()),
  [](const ::testing::TestParamInfo<ResourceEntry_t>& info) {
    // This makes the test output readable (shows the filename)
    std::string name = info.param.name;
    std::replace(name.begin(), name.end(), '.', '_');
    return name;
  });